# Generated by Django 4.1.3 on 2022-11-24 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.CharField(max_length=122)),
                ('Reg_no', models.CharField(max_length=122)),
                ('Address', models.CharField(max_length=122)),
                ('Taluka', models.CharField(max_length=122)),
                ('District', models.CharField(max_length=122)),
                ('State', models.CharField(max_length=122)),
                ('Photo', models.ImageField(upload_to='')),
                ('Pincode', models.IntegerField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.CharField(max_length=120)),
                ('Subject', models.CharField(max_length=122)),
                ('marks', models.IntegerField(max_length=122)),
                ('Semester', models.CharField(max_length=122)),
                ('Year', models.IntegerField(max_length=122)),
                ('Reg_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.student')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.CharField(max_length=120)),
                ('Date', models.DateField()),
                ('Subject', models.CharField(max_length=122)),
                ('Feedback', models.TextField()),
                ('Reg_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.student')),
                ('marks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.marks')),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.CharField(max_length=120)),
                ('Branch', models.CharField(max_length=50)),
                ('Class', models.CharField(max_length=50)),
                ('Date_of_admission', models.IntegerField(max_length=20)),
                ('Semester', models.CharField(max_length=20)),
                ('Reg_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.student')),
            ],
        ),
    ]
