# Generated by Django 4.1.3 on 2022-11-30 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_admission_college_email_alter_student_photo'),
        ('data', '0003_alter_admission_phoneno'),
    ]

    operations = [
    ]
